version: '3.8'

services:
  # 1. BAZA DE DATE
  db:
    image: postgres:15
    container_name: fleet_db_container
    environment:
      POSTGRES_DB: fleet_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fleet-network
    # --- ADĂUGARE NOUĂ: HEALTHCHECK ---
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d fleet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. GATEWAY (Java)
  gateway:
    build: ./gateway_service
    container_name: gateway_container
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fleet_db
    depends_on:
      db:
        condition: service_healthy  # <--- AICI e secretul: Așteaptă healthcheck-ul!
    networks:
      - fleet-network

  # 3. MICROSERVICIU RUTARE (C++)
  route-service:
    build: ./route_service
    container_name: route_engine_container
    ports:
      - "8081:8081"
    networks:
      - fleet-network

  # 4. FRONTEND
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:80"
    networks:
      - fleet-network

volumes:
  postgres_data:

networks:
  fleet-network:
    driver: bridge